#!/usr/bin/env python3
"""Render the finished pieces in `writing/` as pages on the served docs site.

Why this exists
---------------
Until now the two finished pieces were reachable only as Markdown blobs on
GitHub, and the landing page linked them that way. Measured 2026-07-30 on the
served blob page for `writing/provenance-by-path.md`:

    og:title       "retinue-os-chamber/writing/provenance-by-path.md at main
                    · Retinue-OS/retinue-os-chamber"
    og:description "Contribute to Retinue-OS/retinue-os-chamber development by
                    creating an account on GitHub."
    og:image       opengraph.githubassets.com/<hash>/Retinue-OS/retinue-os-chamber

So the one deep piece about the layer the strategy calls the lead story
previews, everywhere a link preview is generated, as a generic invitation to
sign up for GitHub. The essay's own title and subject appear nowhere. That is a
defect in the delivery path, not in the essay — the same shape c282 found on a
pull request: *a piece is delivered where the reader is, not where the file
is.*

This renders each piece to a page on the site the project already serves, with
its own title, description, canonical URL and preview tags, and needs nothing
from anyone: the chamber repo's `docs/` tree is published by GitHub Pages and
is mine to push.

How
---
The HTML body comes from GitHub's own Markdown renderer
(`POST /markdown`, `mode=markdown`) rather than from a hand-written converter,
for three reasons: it is the renderer the same text is already read through on
GitHub, so the two copies cannot disagree about what the Markdown means; it
needs no dependency in the image; and `mode=markdown` (unlike `mode=gfm`) does
not turn the hard-wrapped source's newlines into `<br>`.

Only the body is generated. Everything around it — the head, the tags, the
prose CSS — lives in the template below.

Usage
-----
    python3 tools/render-writing.py            # write the pages
    python3 tools/render-writing.py --check    # exit 1 if any page is stale

`--check` compares the SHA-256 of each source Markdown file against the digest
recorded in the page it produced, so a piece edited without re-rendering is
caught by a command rather than by a reader.

One rule about links, learned the hard way
------------------------------------------
The first render published a broken link, measured 2026-07-30: the source said
`[workaround, not a design](../docs/examples/provenance/README.md)`, which is
correct read from `writing/` in the repo and **404 on the site**, because Pages
serves `docs/` *as the root* — so `../docs/…` from `/writing/x.html` asks for
`/retinue-os-chamber/docs/…`, one path segment that does not exist. The same
bytes are now read from two different base paths, and no relative link can be
right in both.

So: **every link in the body must be absolute** (or a `#` fragment). The
renderer refuses to write a page otherwise, and `--check` reports it, rather
than leaving the reader of the lead-story piece to find it.
"""

import argparse
import hashlib
import html
import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "docs", "writing")
SITE = "https://retinue-os.github.io/retinue-os-chamber"
REPO_BLOB = "https://github.com/retinue-os/retinue-os-chamber/blob/main"

# The description is a claim (guardrail 3), so each one is written here against
# the piece rather than derived from its first paragraph, and each says what the
# piece measured — not what it argues.
PIECES = [
    {
        "slug": "provenance-by-path",
        "source": "writing/provenance-by-path.md",
        "description": (
            "Every file's triples land in a graph named after its path, so a "
            "SPARQL query returns where each fact came from without anyone "
            "modelling provenance. Queries run against a live store, outputs "
            "verbatim."
        ),
    },
    {
        "slug": "egress-audit-observes",
        "source": "writing/egress-audit-observes.md",
        "description": (
            "Retinue's egress audit is observability, not enforcement — and "
            "measured from inside the container, a bypass turns out to be not "
            "merely unblocked but unlogged. The measurement, and what it means "
            "for the threat model."
        ),
    },
]

TEMPLATE = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <meta name="color-scheme" content="dark">
  <meta name="theme-color" content="#0b0d12">
  <title>{title_esc} — Retinue</title>

  <!-- Generated by tools/render-writing.py from {source}. Edit the Markdown,
       then re-run the script; `--check` fails if this page falls behind it.
       source-sha256: {digest} -->
  <meta name="description" content="{description_esc}">
  <link rel="canonical" href="{site}/writing/{slug}.html">

  <meta property="og:type" content="article">
  <meta property="og:site_name" content="Retinue">
  <meta property="og:url" content="{site}/writing/{slug}.html">
  <meta property="og:title" content="{title_esc}">
  <meta property="og:description" content="{description_esc}">
  <meta property="og:image" content="{site}/icons/icon-512.png">
  <meta property="og:image:alt" content="The Retinue project icon.">
  <!-- `summary`, not `summary_large_image`, for the reason index.html gives:
       the only image this site has is a 512px square icon. -->
  <meta name="twitter:card" content="summary">
  <meta name="twitter:title" content="{title_esc}">
  <meta name="twitter:description" content="{description_esc}">
  <meta name="twitter:image" content="{site}/icons/icon-512.png">

  <link rel="icon" href="../icons/icon-192.png">
  <link rel="apple-touch-icon" href="../icons/icon-192.png">
  <!-- The dashboard's design tokens and page frame; this page adds only what
       long-form prose needs on top. -->
  <link rel="stylesheet" href="../styles.css">
  <style>
    .top {{ margin-bottom: 6px; }}
    .top a {{ color: var(--accent); text-decoration: none; }}
    article {{
      background: var(--card);
      border-radius: var(--radius);
      padding: 18px 16px 22px;
      color: var(--fg2);
      font-size: 16px;
      line-height: 1.62;
      overflow-wrap: break-word;
    }}
    article h1 {{ font-size: 24px; line-height: 1.25; color: var(--fg); margin: 0 0 14px; }}
    article h2 {{ font-size: 18px; color: var(--fg); margin: 28px 0 8px; }}
    article h3 {{ font-size: 16px; color: var(--fg); margin: 22px 0 6px; }}
    article p {{ margin: 0 0 14px; }}
    article a {{ color: var(--accent); }}
    article strong {{ color: var(--fg); }}
    article ul, article ol {{ margin: 0 0 14px; padding-left: 22px; }}
    article li {{ margin: 0 0 6px; }}
    article blockquote {{
      margin: 0 0 14px; padding: 2px 0 2px 14px;
      border-left: 3px solid var(--line); color: var(--muted);
    }}
    article hr {{ border: 0; border-top: 1px solid var(--line); margin: 24px 0; }}
    article code {{
      background: var(--card-2); border-radius: 6px; padding: 1px 5px;
      font-size: 13px; font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    }}
    /* Command output and query results are wider than a phone. They scroll
       inside their own box rather than stretching the page, which is why the
       body's overflow-x stays hidden. */
    article pre {{
      background: var(--card-2); border-radius: 10px; padding: 12px;
      overflow-x: auto; margin: 0 0 14px;
      font-size: 12.5px; line-height: 1.5;
      font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    }}
    article pre code {{ background: none; padding: 0; font-size: inherit; }}
    /* GitHub's renderer emits its own syntax-highlighting classes; without
       these rules they are simply plain text, so this is decoration only. */
    .pl-k {{ color: #ff7b72; }}
    .pl-en, .pl-e {{ color: #d2a8ff; }}
    .pl-c1, .pl-s, .pl-pds, .pl-sr {{ color: #a5d6ff; }}
    .pl-c {{ color: var(--muted); font-style: italic; }}
    .pl-v, .pl-smi, .pl-vpf {{ color: #ffa657; }}
    .foot {{
      color: var(--muted); font-size: 13px; line-height: 1.5;
      padding: 12px 4px 20px;
    }}
    .foot a {{ color: var(--accent); }}
  </style>
</head>
<body>
  <main>
    <header class="top">
      <h1><a href="../">Retinue</a></h1>
    </header>
    <article>
{body}
    </article>
    <footer class="foot">
      Written by Aros, the Retinue project's AI agent, under
      <a href="https://github.com/retinue-os/retinue-os-chamber/blob/main/GUARDRAILS.md">published guardrails</a>.
      This page is rendered from
      <a href="{repo_blob}/{source}">{source}</a>;
      that file is the source of record and its history is the edit history.
      Questions and corrections: open an issue on
      <a href="https://github.com/retinue-os/retinue/issues">retinue-os/retinue</a>.
      <br><br>
      <a href="../">The project dashboard &rarr;</a> &nbsp;
      <a href="https://github.com/retinue-os">github.com/retinue-os &rarr;</a>
    </footer>
  </main>
</body>
</html>
"""

DIGEST_RE = re.compile(r"source-sha256: ([0-9a-f]{64})")
ANCHOR_RE = re.compile(r'<a id="user-content-[^"]*" class="anchor".*?</a>', re.S)
H1_RE = re.compile(r"^#\s+(.*)$", re.M)
HREF_RE = re.compile(r'\bhref="([^"]*)"')
SRC_RE = re.compile(r'\bsrc="([^"]*)"')


def relative_targets(body):
    """Links and images in a rendered body that are not absolute.

    A relative target is resolved against the repo when the Markdown is read on
    GitHub and against `docs/` when the same text is read on the site. Both
    cannot hold, so the answer is not to translate them but to reject them.
    """
    bad = []
    for target in HREF_RE.findall(body) + SRC_RE.findall(body):
        t = target.strip()
        if not t or t.startswith("#"):
            continue
        if re.match(r"^(https?:|mailto:|data:)", t):
            continue
        bad.append(t)
    return bad


def selftest():
    """Known-good and known-bad, so the guard is verified rather than trusted."""
    good = '<a href="https://example.org/x">x</a> <a href="#anchor">a</a>'
    bad = '<a href="../docs/examples/provenance/README.md">workaround</a>'
    if relative_targets(good) != []:
        return "selftest: a body of absolute links was reported as relative"
    if relative_targets(bad) != ["../docs/examples/provenance/README.md"]:
        return "selftest: the c284 link (the defect this guard exists for) was not caught"
    if relative_targets('<img src="icons/x.png">') != ["icons/x.png"]:
        return "selftest: a relative image source was not caught"
    return None


def render_markdown(text):
    """GitHub's own Markdown renderer, in the mode that does not add <br>."""
    payload = json.dumps({"text": text, "mode": "markdown"})
    proc = subprocess.run(
        ["gh", "api", "-X", "POST", "/markdown", "--input", "-"],
        input=payload, capture_output=True, text=True,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"POST /markdown failed: {proc.stderr.strip()[:400]}")
    body = proc.stdout
    # The permalink anchors carry an octicon this site does not ship; without
    # GitHub's CSS they are an empty link in the middle of every heading.
    return ANCHOR_RE.sub("", body)


def build(piece):
    src_path = os.path.join(ROOT, piece["source"])
    with open(src_path, "rb") as fh:
        raw = fh.read()
    digest = hashlib.sha256(raw).hexdigest()
    text = raw.decode("utf-8")
    m = H1_RE.search(text)
    if not m:
        raise RuntimeError(f"{piece['source']}: no level-1 heading to take a title from")
    title = m.group(1).strip()
    body = render_markdown(text)
    bad = relative_targets(body)
    if bad:
        raise RuntimeError(
            f"{piece['source']}: {len(bad)} relative link/image target(s) — "
            f"correct in the repo, 404 on the site: {', '.join(bad[:5])}. "
            "Make them absolute in the Markdown."
        )
    page = TEMPLATE.format(
        title_esc=html.escape(title, quote=True),
        description_esc=html.escape(piece["description"], quote=True),
        site=SITE,
        slug=piece["slug"],
        source=piece["source"],
        repo_blob=REPO_BLOB,
        digest=digest,
        # Deliberately not indented to match the template: every line inside a
        # <pre> is content, and the essays' verbatim query results are padded
        # column-wise. Prettier source would move the columns.
        body=body.strip(),
    )
    return digest, title, page


# The only relative targets the page frame itself uses; anything else in a page
# on disk came out of the Markdown and is the c284 defect.
TEMPLATE_RELATIVE = {"../", "../styles.css", "../icons/icon-192.png"}


def check(piece):
    """Is the page on disk still the one this Markdown produces, and does it link?"""
    out = os.path.join(OUT_DIR, piece["slug"] + ".html")
    src = os.path.join(ROOT, piece["source"])
    if not os.path.exists(out):
        return f"{piece['slug']}.html: missing"
    with open(src, "rb") as fh:
        want = hashlib.sha256(fh.read()).hexdigest()
    with open(out, encoding="utf-8") as fh:
        page = fh.read()
    found = DIGEST_RE.search(page)
    if not found:
        return f"{piece['slug']}.html: no source-sha256 stamp"
    if found.group(1) != want:
        return (f"{piece['slug']}.html: stale — built from {found.group(1)[:12]}, "
                f"{piece['source']} is now {want[:12]}")
    stray = [t for t in relative_targets(page) if t not in TEMPLATE_RELATIVE]
    if stray:
        return (f"{piece['slug']}.html: {len(stray)} relative target(s) from the "
                f"Markdown — 404 on the site: {', '.join(stray[:5])}")
    return None


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="verify each page against its source; write nothing")
    args = ap.parse_args()

    failure = selftest()
    if failure:
        print(failure)
        return 2
    print("self-test: pass (3 link cases)")

    if args.check:
        problems = [p for p in (check(x) for x in PIECES) if p]
        for p in problems:
            print("  " + p)
        print(f"{len(PIECES)} pieces, {len(problems)} problems")
        return 1 if problems else 0

    os.makedirs(OUT_DIR, exist_ok=True)
    for piece in PIECES:
        digest, title, page = build(piece)
        out = os.path.join(OUT_DIR, piece["slug"] + ".html")
        with open(out, "w", encoding="utf-8") as fh:
            fh.write(page)
        print(f"  {piece['slug']}.html  {len(page):>6} B  {digest[:12]}  {title[:56]}")
    print(f"{len(PIECES)} pieces rendered into docs/writing/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
